export const TICKETS_ACTION_TYPES = {
  FETCH_TICKETS_START: 'tickets/FETCH_TICKETS_START',
  SET_LOADING: 'tickets/SET_LOADING',
  FETCH_TICKETS_SUCCESS: 'tickets/FETCH_TICKETS_SUCCESS',
  FETCH_TICKETS_FAILURE: 'tickets/FETCH_TICKETS_FAILURE',
};
