export const FILTERS_ACTION_TYPES = {
  SET_CHECKED_ALL_FILTER: 'filters/SET_CHECKED_ALL_FILTER',
  SET_ALL_FLIGHT_FILTER: 'filters/SET_ALL_FLIGHT_FILTER',
  SET_DIRECT_FLIGHT_FILTER: 'filters/SET_DIRECT_FLIGHT_FILTER',
  SET_ONE_STOP_FLIGHT_FILTER: 'filters/SET_ONE_STOP_FLIGHT_FILTER',
  SET_TWO_STOPS_FLIGHT_FILTER: 'filters/SET_TWO_STOPS_FLIGHT_FILTER',
  SET_THREE_STOPS_FLIGHT_FILTER: 'filters/SET_THREE_STOPS_FLIGHT_FILTER',
};
